In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Environment ready ✅")
print("Pandas version:", pd.__version__)

Environment ready ✅
Pandas version: 3.0.5

In [24]:
import pandas as pd

raw_path = r"E:\cyclocast_module1\data\raw\ibtracs.NI.list.v04r01.csv"
df = pd.read_csv(raw_path, low_memory=False)

print("Shape of dataset:", df.shape)
df.head()

Shape of dataset: (62849, 174)

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,...,BOM_GUST_PER,REUNION_GUST,REUNION_GUST_PER,USA_SEAHGT,USA_SEARAD_NE,USA_SEARAD_SE,USA_SEARAD_SW,USA_SEARAD_NW,STORM_SPEED,STORM_DIR
0,,Year,,,,,,,degrees_north,degrees_east,...,second,kts,second,ft,nmile,nmile,nmile,nmile,kts,degrees
1,1842298N11080,1842,1,NI,BB,UNNAMED,1842-10-25 03:00:00,NR,10.9,80.3,...,,,,,,,,,9,265
2,1842298N11080,1842,1,NI,BB,UNNAMED,1842-10-25 06:00:00,NR,10.9,79.8,...,,,,,,,,,9,265
3,1842298N11080,1842,1,NI,BB,UNNAMED,1842-10-25 09:00:00,NR,10.8,79.4,...,,,,,,,,,9,265
4,1842298N11080,1842,1,NI,BB,UNNAMED,1842-10-25 12:00:00,NR,10.8,78.9,...,,,,,,,,,9,265

In [7]:
# See all column names
print(list(df.columns))

['SID', 'SEASON', 'NUMBER', 'BASIN', 'SUBBASIN', 'NAME', 'ISO_TIME', 'NATURE', 'LAT', 'LON', 'WMO_WIND', 'WMO_PRES', 'WMO_AGENCY', 'TRACK_TYPE', 'DIST2LAND', 'LANDFALL', 'IFLAG', 'USA_AGENCY', 'USA_ATCF_ID', 'USA_LAT', 'USA_LON', 'USA_RECORD', 'USA_STATUS', 'USA_WIND', 'USA_PRES', 'USA_SSHS', 'USA_R34_NE', 'USA_R34_SE', 'USA_R34_SW', 'USA_R34_NW', 'USA_R50_NE', 'USA_R50_SE', 'USA_R50_SW', 'USA_R50_NW', 'USA_R64_NE', 'USA_R64_SE', 'USA_R64_SW', 'USA_R64_NW', 'USA_POCI', 'USA_ROCI', 'USA_RMW', 'USA_EYE', 'TOKYO_LAT', 'TOKYO_LON', 'TOKYO_GRADE', 'TOKYO_WIND', 'TOKYO_PRES', 'TOKYO_R50_DIR', 'TOKYO_R50_LONG', 'TOKYO_R50_SHORT', 'TOKYO_R30_DIR', 'TOKYO_R30_LONG', 'TOKYO_R30_SHORT', 'TOKYO_LAND', 'CMA_LAT', 'CMA_LON', 'CMA_CAT', 'CMA_WIND', 'CMA_PRES', 'HKO_LAT', 'HKO_LON', 'HKO_CAT', 'HKO_WIND', 'HKO_PRES', 'KMA_LAT', 'KMA_LON', 'KMA_CAT', 'KMA_WIND', 'KMA_PRES', 'KMA_R50_DIR', 'KMA_R50_LONG', 'KMA_R50_SHORT', 'KMA_R30_DIR', 'KMA_R30_LONG', 'KMA_R30_SHORT', 'NEWDELHI_LAT', 'NEWDELHI_LON', 'NEWDELHI_GRADE', 'NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_CI', 'NEWDELHI_DP', 'NEWDELHI_POCI', 'REUNION_LAT', 'REUNION_LON', 'REUNION_TYPE', 'REUNION_WIND', 'REUNION_PRES', 'REUNION_TNUM', 'REUNION_CI', 'REUNION_RMW', 'REUNION_R34_NE', 'REUNION_R34_SE', 'REUNION_R34_SW', 'REUNION_R34_NW', 'REUNION_R50_NE', 'REUNION_R50_SE', 'REUNION_R50_SW', 'REUNION_R50_NW', 'REUNION_R64_NE', 'REUNION_R64_SE', 'REUNION_R64_SW', 'REUNION_R64_NW', 'BOM_LAT', 'BOM_LON', 'BOM_TYPE', 'BOM_WIND', 'BOM_PRES', 'BOM_TNUM', 'BOM_CI', 'BOM_RMW', 'BOM_R34_NE', 'BOM_R34_SE', 'BOM_R34_SW', 'BOM_R34_NW', 'BOM_R50_NE', 'BOM_R50_SE', 'BOM_R50_SW', 'BOM_R50_NW', 'BOM_R64_NE', 'BOM_R64_SE', 'BOM_R64_SW', 'BOM_R64_NW', 'BOM_ROCI', 'BOM_POCI', 'BOM_EYE', 'BOM_POS_METHOD', 'BOM_PRES_METHOD', 'NADI_LAT', 'NADI_LON', 'NADI_CAT', 'NADI_WIND', 'NADI_PRES', 'WELLINGTON_LAT', 'WELLINGTON_LON', 'WELLINGTON_WIND', 'WELLINGTON_PRES', 'DS824_LAT', 'DS824_LON', 'DS824_STAGE', 'DS824_WIND', 'DS824_PRES', 'TD9636_LAT', 'TD9636_LON', 'TD9636_STAGE', 'TD9636_WIND', 'TD9636_PRES', 'TD9635_LAT', 'TD9635_LON', 'TD9635_WIND', 'TD9635_PRES', 'TD9635_ROCI', 'NEUMANN_LAT', 'NEUMANN_LON', 'NEUMANN_CLASS', 'NEUMANN_WIND', 'NEUMANN_PRES', 'MLC_LAT', 'MLC_LON', 'MLC_CLASS', 'MLC_WIND', 'MLC_PRES', 'USA_GUST', 'BOM_GUST', 'BOM_GUST_PER', 'REUNION_GUST', 'REUNION_GUST_PER', 'USA_SEAHGT', 'USA_SEARAD_NE', 'USA_SEARAD_SE', 'USA_SEARAD_SW', 'USA_SEARAD_NW', 'STORM_SPEED', 'STORM_DIR']

In [25]:
# Check which basins exist in the data
print(df['BASIN'].unique())

<StringArray>
[' ', 'NI', nan, 'WP']
Length: 4, dtype: str

In [26]:
# Check how many rows belong to the North Indian Ocean basin
print(df[df['BASIN'] == 'NI'].shape)

(57841, 174)

In [27]:
# Look for columns related to wind, pressure, and category
wind_pressure_cols = [col for col in df.columns if 'WIND' in col or 'PRES' in col or 'CAT' in col]
print(wind_pressure_cols)

['WMO_WIND', 'WMO_PRES', 'USA_WIND', 'USA_PRES', 'TOKYO_WIND', 'TOKYO_PRES', 'CMA_CAT', 'CMA_WIND', 'CMA_PRES', 'HKO_CAT', 'HKO_WIND', 'HKO_PRES', 'KMA_CAT', 'KMA_WIND', 'KMA_PRES', 'NEWDELHI_WIND', 'NEWDELHI_PRES', 'REUNION_WIND', 'REUNION_PRES', 'BOM_WIND', 'BOM_PRES', 'BOM_PRES_METHOD', 'NADI_CAT', 'NADI_WIND', 'NADI_PRES', 'WELLINGTON_WIND', 'WELLINGTON_PRES', 'DS824_WIND', 'DS824_PRES', 'TD9636_WIND', 'TD9636_PRES', 'TD9635_WIND', 'TD9635_PRES', 'NEUMANN_WIND', 'NEUMANN_PRES', 'MLC_WIND', 'MLC_PRES']

In [28]:
# Filter to NI basin only, and inspect New Delhi (IMD) columns
ni_df = df[df['BASIN'] == 'NI']

# Check unique values in NEWDELHI_GRADE (likely the category label)
print("NEWDELHI_GRADE unique values:")
print(ni_df['NEWDELHI_GRADE'].unique())

# Check how much data is missing in key columns
cols_to_check = ['ISO_TIME', 'LAT', 'LON', 'NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_GRADE', 'WMO_WIND', 'WMO_PRES', 'SEASON', 'SID', 'NAME']
print("\nMissing value counts (out of", len(ni_df), "rows):")
print(ni_df[cols_to_check].isna().sum())

NEWDELHI_GRADE unique values:
<StringArray>
[' ', 'D', 'DD', 'CS', 'SCS', 'VSCS', 'ESCS', 'SCS(H)', 'SUCS', 'L', 'SuCS']
Length: 11, dtype: str

Missing value counts (out of 57841 rows):
ISO_TIME          0
LAT               0
LON               0
NEWDELHI_WIND     0
NEWDELHI_PRES     0
NEWDELHI_GRADE    0
WMO_WIND          0
WMO_PRES          0
SEASON            0
SID               0
NAME              0
dtype: int64

In [29]:
# Check for blank/space values (not just NaN) in key columns
cols_to_check = ['NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_GRADE', 'WMO_WIND', 'WMO_PRES']

for col in cols_to_check:
    blank_count = (ni_df[col].astype(str).str.strip() == '').sum()
    print(f"{col}: {blank_count} blank rows out of {len(ni_df)}")

NEWDELHI_WIND: 48388 blank rows out of 57841
NEWDELHI_PRES: 49241 blank rows out of 57841
NEWDELHI_GRADE: 48311 blank rows out of 57841
WMO_WIND: 50800 blank rows out of 57841
WMO_PRES: 51237 blank rows out of 57841

In [30]:
# Step 1: Drop the first row (row 0), which contains units, not real data
ni_df = ni_df.drop(index=0, errors='ignore')

# Step 2: Convert SEASON to numeric (this turns text like "1842" into the actual number 1842)
ni_df['SEASON'] = pd.to_numeric(ni_df['SEASON'], errors='coerce')

# Step 3: Check the year range again
print("Year range in NI data:", ni_df['SEASON'].min(), "to", ni_df['SEASON'].max())

# Step 4: Now filter to project's actual date range: 2013–2021
ni_recent = ni_df[(ni_df['SEASON'] >= 2013) & (ni_df['SEASON'] <= 2021)]
print("\nRows in 2013–2021 range:", ni_recent.shape)

# Step 5: Recheck blank counts, but only within 2013–2021
cols_to_check = ['NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_GRADE', 'WMO_WIND', 'WMO_PRES']

for col in cols_to_check:
    blank_count = (ni_recent[col].astype(str).str.strip() == '').sum()
    print(f"{col}: {blank_count} blank rows out of {len(ni_recent)}")

Year range in NI data: 1842 to 2025

Rows in 2013–2021 range: (3415, 174)
NEWDELHI_WIND: 655 blank rows out of 3415
NEWDELHI_PRES: 702 blank rows out of 3415
NEWDELHI_GRADE: 641 blank rows out of 3415
WMO_WIND: 1149 blank rows out of 3415
WMO_PRES: 1151 blank rows out of 3415

In [31]:
# Save the NI-filtered, 2013-2021 filtered raw data (not cleaned yet, just filtered)
output_path = r"E:\cyclocast_module1\data\raw\best_track_raw.csv"
ni_recent.to_csv(output_path, index=False)

print("Saved to:", output_path)
print("Final shape:", ni_recent.shape)

Saved to: E:\cyclocast_module1\data\raw\best_track_raw.csv
Final shape: (3415, 174)

In [32]:
import pandas as pd

raw_path = r"E:\cyclocast_module1\data\raw\best_track_raw.csv"
df = pd.read_csv(raw_path, low_memory=False)

print(df.shape)
df.head()

(3415, 174)

,SID,SEASON,NUMBER,BASIN,SUBBASIN,NAME,ISO_TIME,NATURE,LAT,LON,...,BOM_GUST_PER,REUNION_GUST,REUNION_GUST_PER,USA_SEAHGT,USA_SEARAD_NE,USA_SEARAD_SE,USA_SEARAD_SW,USA_SEARAD_NW,STORM_SPEED,STORM_DIR
0,2013130N04093,2013,20,NI,BB,MAHASEN:VIYARU,2013-05-09 18:00:00,DS,4.4,93.0,...,,,,,,,,,7,85
1,2013130N04093,2013,20,NI,BB,MAHASEN:VIYARU,2013-05-09 21:00:00,DS,4.4,93.3,...,,,,,,,,,5,80
2,2013130N04093,2013,20,NI,BB,MAHASEN:VIYARU,2013-05-10 00:00:00,TS,4.5,93.5,...,,,,,,,,,3,0
3,2013130N04093,2013,20,NI,BB,MAHASEN:VIYARU,2013-05-10 03:00:00,TS,4.7,93.3,...,,,,,,,,,6,310
4,2013130N04093,2013,20,NI,BB,MAHASEN:VIYARU,2013-05-10 06:00:00,TS,4.9,93.0,...,,,,,,,,,8,300

In [17]:
# Keep only the essential columns
columns_needed = ['SID', 'NAME', 'SEASON', 'ISO_TIME', 'LAT', 'LON', 
                   'NEWDELHI_WIND', 'NEWDELHI_PRES', 'NEWDELHI_GRADE']

clean_df = df[columns_needed].copy()
print(clean_df.shape)
clean_df.head()

(3415, 9)

,SID,NAME,SEASON,ISO_TIME,LAT,LON,NEWDELHI_WIND,NEWDELHI_PRES,NEWDELHI_GRADE
0,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 18:00:00,4.4,93.0,,,
1,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 21:00:00,4.4,93.3,,,
2,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 00:00:00,4.5,93.5,,,
3,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 03:00:00,4.7,93.3,,,
4,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 06:00:00,4.9,93.0,,,

In [33]:
clean_df = clean_df.rename(columns={
    'SID': 'storm_id',
    'NAME': 'storm_name',
    'SEASON': 'year',
    'ISO_TIME': 'timestamp',
    'LAT': 'lat',
    'LON': 'lon',
    'NEWDELHI_WIND': 'wind_speed',
    'NEWDELHI_PRES': 'pressure',
    'NEWDELHI_GRADE': 'category'
})

clean_df.head()

,storm_id,storm_name,year,timestamp,lat,lon,wind_speed,pressure,category
0,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 18:00:00,4.4,93.0,NaN,NaN,NaN
1,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 21:00:00,4.4,93.3,NaN,NaN,NaN
2,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 00:00:00,4.5,93.5,NaN,NaN,NaN
3,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 03:00:00,4.7,93.3,NaN,NaN,NaN
4,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 06:00:00,4.9,93.0,NaN,NaN,NaN

In [19]:
clean_df['timestamp'] = pd.to_datetime(clean_df['timestamp'], errors='coerce')

print(clean_df['timestamp'].dtype)
clean_df[['storm_id', 'timestamp']].head()

datetime64[us]

        storm_id           timestamp
0  2013130N04093 2013-05-09 18:00:00
1  2013130N04093 2013-05-09 21:00:00
2  2013130N04093 2013-05-10 00:00:00
3  2013130N04093 2013-05-10 03:00:00
4  2013130N04093 2013-05-10 06:00:00

In [34]:
# Convert wind_speed and pressure to numeric (they may currently be text due to blank spaces)
clean_df['wind_speed'] = pd.to_numeric(clean_df['wind_speed'], errors='coerce')
clean_df['pressure'] = pd.to_numeric(clean_df['pressure'], errors='coerce')

# Clean up the category column: strip spaces, replace truly blank entries with NaN
clean_df['category'] = clean_df['category'].astype(str).str.strip()
clean_df['category'] = clean_df['category'].replace('', pd.NA)

clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3415 entries, 0 to 3414
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   storm_id    3415 non-null   str
 1   storm_name  3415 non-null   str
 2   year        3415 non-null   int64
 3   timestamp   3415 non-null   datetime64[us]
 4   lat         3415 non-null   float64
 5   lon         3415 non-null   float64
 6   wind_speed  2760 non-null   float64
 7   pressure    2713 non-null   float64
 8   category    2774 non-null   str
dtypes: datetime64[us](1), float64(4), int64(1), str(3)
memory usage: 240.2 KB

In [35]:
print("Missing timestamp:", clean_df['timestamp'].isna().sum())
print("Missing wind_speed:", clean_df['wind_speed'].isna().sum())
print("Missing pressure:", clean_df['pressure'].isna().sum())
print("Missing category:", clean_df['category'].isna().sum())
print("Total rows:", len(clean_df))

Missing timestamp: 0
Missing wind_speed: 655
Missing pressure: 702
Missing category: 641
Total rows: 3415

In [36]:
# Final look before saving
print(clean_df.dtypes)
print("\nFinal shape:", clean_df.shape)
clean_df.head(10)

storm_id                 str
storm_name               str
year                   int64
timestamp     datetime64[us]
lat                  float64
lon                  float64
wind_speed           float64
pressure             float64
category                 str
dtype: object

Final shape: (3415, 9)

,storm_id,storm_name,year,timestamp,lat,lon,wind_speed,pressure,category
0,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 18:00:00,4.4,93.0,NaN,NaN,NaN
1,2013130N04093,MAHASEN:VIYARU,2013,2013-05-09 21:00:00,4.4,93.3,NaN,NaN,NaN
2,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 00:00:00,4.5,93.5,NaN,NaN,NaN
3,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 03:00:00,4.7,93.3,NaN,NaN,NaN
4,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 06:00:00,4.9,93.0,NaN,NaN,NaN
5,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 09:00:00,5.1,92.6,25.0,1004.0,D
6,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 12:00:00,5.4,92.3,30.0,1002.0,DD
7,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 15:00:00,5.8,92.0,30.0,1001.0,DD
8,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 18:00:00,6.1,91.7,30.0,1000.0,DD
9,2013130N04093,MAHASEN:VIYARU,2013,2013-05-10 21:00:00,6.4,91.3,30.0,999.0,DD

In [37]:
clean_path = r"E:\cyclocast_module1\data\clean\best_track_clean.csv"
clean_df.to_csv(clean_path, index=False)

print("Saved to:", clean_path)
print("Final shape:", clean_df.shape)

Saved to: E:\cyclocast_module1\data\clean\best_track_clean.csv
Final shape: (3415, 9)